# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: peer
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: kafka
        image: quay.io/coffeepac/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk:2181/kafka"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        imagePullPolicy: Always 
  #volumeClaimTemplates:
  #- metadata:
  #    name: datadir
  #    annotations:
  #      volume.alpha.kubernetes.io/storage-class: anything
  ##  spec:
   #   accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 20Gi
