# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: peer
  clusterIP: None
  selector:
    app: kafka
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      serviceAccount: default
      containers:
        - name: kafka
          image: quay.io/coffeepac/kafka:latest
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zk:2181/kafka
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          imagePullPolicy: Always